// <auto-generated />
using System;
using AstroTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AstroTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstroTrack.Models.Checkpoint", b =>
                {
                    b.Property<long>("IdCheckpoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CHECKPOINT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCheckpoint"));

                    b.Property<int>("BotaoPanico")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("BOTAO_PANICO");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<long>("IdViagem")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VIAGEM");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(10,7)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(10,7)")
                        .HasColumnName("LONGITUDE");

                    b.Property<int>("PortaAberta")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PORTA_ABERTA");

                    b.HasKey("IdCheckpoint");

                    b.HasIndex("IdViagem");

                    b.ToTable("AT_CHECKPOINTS", (string)null);
                });

            modelBuilder.Entity("AstroTrack.Models.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(18)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdCliente");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AT_CLIENTES", (string)null);
                });

            modelBuilder.Entity("AstroTrack.Models.Motorista", b =>
                {
                    b.Property<long>("IdMotorista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTORISTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMotorista"));

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(11)")
                        .HasColumnName("CNH");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("IdMotorista");

                    b.HasIndex("Cnh")
                        .IsUnique();

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("AT_MOTORISTAS", (string)null);
                });

            modelBuilder.Entity("AstroTrack.Models.UsuarioSistema", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(60)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Email");

                    b.ToTable("AT_USUARIOS_SISTEMA", (string)null);
                });

            modelBuilder.Entity("AstroTrack.Models.Veiculo", b =>
                {
                    b.Property<long>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VEICULO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdVeiculo"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(60)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(80)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(7)")
                        .HasColumnName("PLACA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("AT_VEICULOS", (string)null);
                });

            modelBuilder.Entity("AstroTrack.Models.Viagem", b =>
                {
                    b.Property<long>("IdViagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VIAGEM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdViagem"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INICIO");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("DESTINO");

                    b.Property<long>("IdCliente")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<long>("IdMotorista")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTORISTA");

                    b.Property<long>("IdVeiculo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VEICULO");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("ORIGEM");

                    b.Property<decimal>("QuilometragemTotal")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("QUILOMETRAGEM_TOTAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdViagem");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMotorista");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("AT_VIAGENS", (string)null);
                });

            modelBuilder.Entity("AstroTrack.Models.Checkpoint", b =>
                {
                    b.HasOne("AstroTrack.Models.Viagem", "Viagem")
                        .WithMany("Checkpoints")
                        .HasForeignKey("IdViagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("AstroTrack.Models.Viagem", b =>
                {
                    b.HasOne("AstroTrack.Models.Cliente", "Cliente")
                        .WithMany("Viagens")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AstroTrack.Models.Motorista", "Motorista")
                        .WithMany("Viagens")
                        .HasForeignKey("IdMotorista")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AstroTrack.Models.Veiculo", "Veiculo")
                        .WithMany("Viagens")
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Motorista");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("AstroTrack.Models.Cliente", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("AstroTrack.Models.Motorista", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("AstroTrack.Models.Veiculo", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("AstroTrack.Models.Viagem", b =>
                {
                    b.Navigation("Checkpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
